CREATE DATABASE IF NOT EXISTS hello DEFAULT CHARACTER SET utf8mb4
COLLATE UTF8MB4_0900_AI_CI;

USE oppnysfiles;


CREATE TABLE IF NOT EXISTS `file`(
  `id` INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  `message` VARCHAR(256) COMMENT '文件名称'
);